name: Setup
description: Setup Bun and install dependencies

inputs:
  node:
    description: 'Setup Node.js for npm publishing'
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: 1.3.9

    - name: Setup Node
      if: inputs.node == 'true'
      uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
      with:
        node-version: '24.13.0'
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      run: bun install --frozen-lockfile
      shell: bash
